export const assets = {
  search: require('./search/search.png'),
  notification: require('./notification/notification.png'),
  flag_1: require('./flags/1/1.png'),
  flag_2: require('./flags/2/2.png'),
  banner: require('./banner/1.png'),
  badminton: require('./balls/badminton/badminton.png'),
  baseball: require('./balls/baseball/baseball.png'),
  basketball: require('./balls/basketball/basketball.png'),
  soccer: require('./balls/soccer/soccer.png'),
  tennis: require('./balls/tennis/tennis.png'),
  volly: require('./balls/volly/volly.png'),
  pingpong: require('./balls/pingpong/pingpong.png'),
  football: require('./balls/football/football.png'),
  arsenal: require('./club/arsenal/arsenal.png'),
  astonvilla: require('./club/astonvilla/astonvilla.png'),
  chelsea: require('./club/chelsea/chelsea.png'),
  charlton_athletic: require('./club/CharltonAthletic/CharltonAthletic.png'),
  manchester: require('./club/manchester/manchester.png'),
  middlesbrough: require('./club/Middlesbrough/Middlesbrough.png'),
  swansea_city: require('./club/swanseaCity/swanseaCity.png'),
  tottenham: require('./club/tottenham/tottenham.png'),
  real_betis: require('./club/real-betis/Real-Betis.png'),
  valencia: require('./club/valencia/valencia.png'),

  home: require('./outlines/home/Home.png'),
  chart: require('./outlines/chart/Chart.png'),
  discovery: require('./outlines/discovery/Discovery.png'),
  profile: require('./outlines/profile/Profile.png'),
};
