"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DEFAULT_VISIBLE_CHEVRON = exports.DEFAULT_UNMOUNTED_CONTENT_ACCORDION = exports.DEFAULT_TINT_CHEVRON = exports.DEFAULT_SIZE_TINT_CHEVRON = exports.DEFAULT_PROGRESS_LOADING_API = exports.DEFAULT_INITIAL_MOUNTED_CONTENT_ACCORDION = exports.DEFAULT_INACTIVE_BACKGROUND_CHEVRON = exports.DEFAULT_HEIGHT_CONTENT = exports.DEFAULT_EXPANDED_CONTENT_ACCORDION = exports.DEFAULT_DISABLED_HEAD_ACCORDION = exports.DEFAULT_CONTENT_HEIGHT = exports.DEFAULT_ACTIVE_BACKGROUND_CHEVRON = void 0;
const DEFAULT_INITIAL_MOUNTED_CONTENT_ACCORDION = true;
exports.DEFAULT_INITIAL_MOUNTED_CONTENT_ACCORDION = DEFAULT_INITIAL_MOUNTED_CONTENT_ACCORDION;
const DEFAULT_UNMOUNTED_CONTENT_ACCORDION = false;
exports.DEFAULT_UNMOUNTED_CONTENT_ACCORDION = DEFAULT_UNMOUNTED_CONTENT_ACCORDION;
const DEFAULT_INACTIVE_BACKGROUND_CHEVRON = '#fff0e4';
exports.DEFAULT_INACTIVE_BACKGROUND_CHEVRON = DEFAULT_INACTIVE_BACKGROUND_CHEVRON;
const DEFAULT_EXPANDED_CONTENT_ACCORDION = false;
exports.DEFAULT_EXPANDED_CONTENT_ACCORDION = DEFAULT_EXPANDED_CONTENT_ACCORDION;
const DEFAULT_ACTIVE_BACKGROUND_CHEVRON = '#e5f6ff';
exports.DEFAULT_ACTIVE_BACKGROUND_CHEVRON = DEFAULT_ACTIVE_BACKGROUND_CHEVRON;
const DEFAULT_DISABLED_HEAD_ACCORDION = false;
exports.DEFAULT_DISABLED_HEAD_ACCORDION = DEFAULT_DISABLED_HEAD_ACCORDION;
const DEFAULT_PROGRESS_LOADING_API = false;
exports.DEFAULT_PROGRESS_LOADING_API = DEFAULT_PROGRESS_LOADING_API;
const DEFAULT_SIZE_TINT_CHEVRON = 16; // height x width

exports.DEFAULT_SIZE_TINT_CHEVRON = DEFAULT_SIZE_TINT_CHEVRON;
const DEFAULT_VISIBLE_CHEVRON = true;
exports.DEFAULT_VISIBLE_CHEVRON = DEFAULT_VISIBLE_CHEVRON;
const DEFAULT_CONTENT_HEIGHT = 100;
exports.DEFAULT_CONTENT_HEIGHT = DEFAULT_CONTENT_HEIGHT;
const DEFAULT_HEIGHT_CONTENT = 0; //optimize method

exports.DEFAULT_HEIGHT_CONTENT = DEFAULT_HEIGHT_CONTENT;
const DEFAULT_TINT_CHEVRON = '#16182b';
exports.DEFAULT_TINT_CHEVRON = DEFAULT_TINT_CHEVRON;
//# sourceMappingURL=constant.js.map